language: python 
python: 
  - "3.6"
install:
  - pip install pipenv
  - pipenv install

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

scipt:
  - ./manage.py test